@startuml
skinparam legend {
  backgroundColor #GhostWhite
  entrySeparator #GhostWhite
}

legend top
  <#GhostWhite,#GhostWhite>|        |= __Legend__ |
  |<#lightpink>   | UI interactions during experiment or call to ""MoveToNextState""|
  |<#lightgreen>  | Abstract function in ""ExperimentManager"" to be implemented by user|
endlegend

|__in-package__|
start
floating note: ""UninitializedSession""
#lightpink:Click next button ("Load session data") or call ""MoveToNextState"";
floating note
    enters ""AwaitingInitialization""
    then ""AwaitingBlockConfig""
end note
|#FloralWhite|__user-defined__|
:(optional) Set ""UXF.Session.Being"" parameters
with ""ExperimentManager.SessionBeginParams"";
|__in-package__|
#lightpink:Click next button ("Start Session") or call ""MoveToNextState"";
:""OnSessionBegin""  called;
|__user-defined__|
#lightgreen:""OnSessionBegin"";
|#Azure|__in-package__|
/'
 ' #lightpink:Click next button ("Get Config") or call ""MoveToNextState"";
 '/

while (Get config for block from experiment server (""block_data"")) is (not end block)
    :;
    floating note: enters ""ReadyForCalibration""
    #lightpink:Click next button ("Run Calibration") or call ""MoveToNextState"";
    floating note
        enters ""Calibrating"" or
        ""ReadyForBlockBegin"" if no claibration
    end note
    if (calibration function exists) then (yes)
        |__user-defined__|
        :Run calibration;
        :""CalibrationComplete""  called;
        floating note: enters ""ReadyForBlockBegin""
    else (no)
    endif

    |__in-package__|
    :Create new block;
    :""ConfigureBlock""  called with ""block_data"" and new block;

    |__user-defined__|
    #lightgreen:""ConfigureBlock"";

    |__in-package__|
    #lightpink:Click next button ("Run Block") or call ""MoveToNextState"";
    floating note: enters ""BlockBegan""
    :""OnBlockBegin""  called;

    |__user-defined__|
    #lightgreen:""OnBlockBegin"";

    |__in-package__|
    while (trials remaining) is (yes)

        :""OnTrialBegin""  called;

        |__user-defined__|
        #lightgreen:""OnTrialBegin"";

        split
            |__in-package__|
            #lightpink:Cancel button pressed or call ""MoveToNextState"";
        split again
            |__user-defined__|
            :Participant performs trial;
            :Wait for ""EndCurrentTrial"" / ""BeginNextTrial"" call;
        end split

        |__in-package__|
        :""OnTrialEnd""  called;

        |__user-defined__|
        #lightgreen:""OnTrialEnd"";

        |__in-package__|
        if (Was cancel button pressed) then (yes)
            break
        else (no)
            :If  ""BeginNextTrial""  not called, wait for it;
        endif
    endwhile (no)

    :""OnBlockEnd""  called;
    floating note: enters ""BlockEnded"" or ""BlockCancelled""

    |__user-defined__|
    #lightgreen:""OnBlockEnd"";

    |__in-package__|
    if (Cancel button pressed) then (no)
        :Move to next block;
    else (yes)
    endif
    #lightpink:Click next button ("Get Config") or call ""MoveToNextState"";

endwhile (end block)

:""OnSessionEnd""  called;
floating note: enters ""SessionEnded""

|__user-defined__|
#lightgreen:""OnSessionEnd"";

|__in-package__|
stop
@enduml
